CREATE TABLE samples (
  id INT(11) NOT NULL AUTO_INCREMENT,
  code VARCHAR(2) NOT NULL,
  firstname VARCHAR(20) NOT NULL,
  lastname VARCHAR(20) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;